In [14]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf




x = tf.constant(4.0, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [9]:
x = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float32)
print(x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [10]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [11]:
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [12]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [13]:
x = tf.random.normal((3,3), mean=0.0, stddev=1.0)
print(x)

tf.Tensor(
[[-0.5287234  -0.2547118  -0.5006332 ]
 [ 0.20744802 -0.11599975  2.1021695 ]
 [ 1.5847985   0.6745741   0.14004186]], shape=(3, 3), dtype=float32)


In [16]:
x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.43973637 0.00284898 0.51229775]], shape=(1, 3), dtype=float32)


In [17]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [4]:
x = tf.range(start=12, limit=50, delta=7)
print(x)

tf.Tensor([12 19 26 33 40 47], shape=(6,), dtype=int32)


In [10]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x, y)

z = x-y
z = x/y

z = tf.multiply(x, y)

z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [11]:
z = x ** y
print(z)

tf.Tensor([  1  32 729], shape=(3,), dtype=int32)


In [15]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x, y)
print(z)

z = x @ y
print(z)

tf.Tensor(
[[-0.75373995 -0.5481858  -0.09109184 -0.25665998]
 [-2.1505935  -3.1518466   0.39979142 -0.89125097]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.75373995 -0.5481858  -0.09109184 -0.25665998]
 [-2.1505935  -3.1518466   0.39979142 -0.89125097]], shape=(2, 4), dtype=float32)
